name: Deploy to EC2 in nginx

on:
  push:
    branches:
      - main
    paths-ignore:
        - 'README.md'
        - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH using appleboy/ssh-action
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            git config --global --add safe.directory /var/www/html
            git pull origin main
            sudo systemctl restart nginx